### ISSUE TITLE
Blocks <a> tags

### ISSUE THREAD

**Issue by cw789** [Dendrochronologyy/SimplBox#1]
Blocks all other "a" tags without data-simplbox on the same page.
Seems like a preventDefault is working on all anchors.

**Comment by adigitalthing** [comment]
I confirm this.

**Comment by DacoTaco** [comment]
anyone got some information about this?

i really like simplbox (it resizes images !) but this <a> bug is a dealbreaker...
i even added a data-simplbox but still wont work, as in not even showing the overlay which would show simplbox is trying something :/

**Comment by DacoTaco** [comment]
well, i seem to have found the preventdefault doing it.
its the one of quitOnDocumentClick (line 164/165).
disable that one and everything works again. why was it there anyway?

**Comment by ghost** [comment]
You don't need to comment or disable any line, just simply set the option "quitOnDocumentClick: false", for example:

``` javascript
var simplbox = new SimplBox(document.querySelectorAll("[data-simplbox='simplbox-picture']"), {
    quitOnDocumentClick: false
});
simplbox.init();
```

**Comment by DacoTaco** [comment]
ye but maybe you want to keep quit on document? :) 

i for sure have it enabled because i want it

**Comment by cw789** [comment]
Close from my side as not seen as active project.
